#!/usr/bin/env python3

import os
import time
import logging
import multiprocessing as mp

import scripts.tick as tick  # socket stream
import scripts.orderdiff as diff  # socket stream
import scripts.orderbook as book  # http polling


# Start all 3 collection scripts
if __name__ == '__main__':
    # configure loggers
    sh = logging.StreamHandler()
    sh.setLevel(logging.WARNING)
    fh = logging.FileHandler('collect.log')
    fh.setLevel(logging.INFO)
    fmt = logging.Formatter(
        fmt='%(levelname)s %(asctime)s %(pathname)s: %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )
    fh.setFormatter(fmt)

    logger = logging.getLogger('main')
    logger.setLevel(logging.DEBUG)

    logging.getLogger().addHandler(sh)
    logging.getLogger().addHandler(fh)
    logging.getLogger().setLevel(logging.DEBUG)
    logging.getLogger('pysher.connection').setLevel(logging.DEBUG)

    # holds all collection processes
    ps = []

    # read configs and init processes
    for module in (tick, diff, book):
        config = {}
        conf = module.CONFIG_FILE
        if os.path.isfile(conf):
            with open(conf) as f:
                for line in f:
                    name, var = line.partition('=')[::2]
                    config[name.strip()] = eval(var.strip())
        ps.append(mp.Process(target=module.main, kwargs=config))

    # start all collection
    for p in ps:
        p.start()

    # listen and handle termination signals
    while True:
        try:
            time.sleep(0.5)
        except KeyboardInterrupt:
            for p in ps:
                p.terminate()
                logger.debug('SIGTERM sent to %s', p.name)
            break

    # debug log
    for p in ps:
        p.join(5)
        logger.debug('%s joined', p.name)
